# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Parser-CET
version:      0.04
version_from: lib/Template/Parser/CET.pm
installdirs:  site
requires:
    Template:                      2.00
    Template::Alloy:               1.002

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
